/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FeeRecordId = IDL.Text;
export const FeesPaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
  'partial_payment' : IDL.Null,
});
export const StudentId = IDL.Text;
export const FeeRecord = IDL.Record({
  'id' : FeeRecordId,
  'status' : FeesPaymentStatus,
  'month' : IDL.Text,
  'studentId' : StudentId,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
});
export const FeesStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
});
export const TeacherId = IDL.Text;
export const ClassName = IDL.Text;
export const Student = IDL.Record({
  'id' : StudentId,
  'timing' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'feesStatus' : FeesStatus,
  'mobileNumber' : IDL.Text,
  'assignedTeacherId' : TeacherId,
  'fatherName' : IDL.Text,
  'monthlyFees' : IDL.Nat,
  'className' : ClassName,
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
});
export const AcademicRecordId = IDL.Text;
export const AcademicRecord = IDL.Record({
  'id' : AcademicRecordId,
  'studentId' : StudentId,
  'monthlyProgress' : IDL.Text,
  'updatedAt' : IDL.Int,
  'previousSabak' : IDL.Text,
  'currentSabak' : IDL.Text,
  'akhlaqRating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const AttendanceId = IDL.Text;
export const AttendanceStatus = IDL.Variant({
  'on_leave' : IDL.Null,
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'markedBy' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFeeRecord' : IDL.Func([FeeRecord], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'addTeacher' : IDL.Func([Teacher], [], []),
  'deleteStudent' : IDL.Func([StudentId], [], []),
  'deleteTeacher' : IDL.Func([TeacherId], [], []),
  'getAcademicRecord' : IDL.Func([StudentId], [AcademicRecord], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMonthlyAttendance' : IDL.Func(
      [StudentId, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [Student], ['query']),
  'getStudentAttendance' : IDL.Func(
      [StudentId],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getStudentFees' : IDL.Func([StudentId], [IDL.Vec(FeeRecord)], ['query']),
  'getStudentsByClass' : IDL.Func([ClassName], [IDL.Vec(Student)], ['query']),
  'getStudentsByTeacher' : IDL.Func([TeacherId], [IDL.Vec(Student)], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [Teacher], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'markAttendance' : IDL.Func([Attendance], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAcademicRecord' : IDL.Func([AcademicRecord], [], []),
  'updateFeeStatus' : IDL.Func([FeeRecordId, FeesPaymentStatus], [], []),
  'updateStudent' : IDL.Func([StudentId, Student], [], []),
  'updateTeacher' : IDL.Func([TeacherId, Teacher], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FeeRecordId = IDL.Text;
  const FeesPaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
    'partial_payment' : IDL.Null,
  });
  const StudentId = IDL.Text;
  const FeeRecord = IDL.Record({
    'id' : FeeRecordId,
    'status' : FeesPaymentStatus,
    'month' : IDL.Text,
    'studentId' : StudentId,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const FeesStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
  });
  const TeacherId = IDL.Text;
  const ClassName = IDL.Text;
  const Student = IDL.Record({
    'id' : StudentId,
    'timing' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'feesStatus' : FeesStatus,
    'mobileNumber' : IDL.Text,
    'assignedTeacherId' : TeacherId,
    'fatherName' : IDL.Text,
    'monthlyFees' : IDL.Nat,
    'className' : ClassName,
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
  });
  const AcademicRecordId = IDL.Text;
  const AcademicRecord = IDL.Record({
    'id' : AcademicRecordId,
    'studentId' : StudentId,
    'monthlyProgress' : IDL.Text,
    'updatedAt' : IDL.Int,
    'previousSabak' : IDL.Text,
    'currentSabak' : IDL.Text,
    'akhlaqRating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const AttendanceId = IDL.Text;
  const AttendanceStatus = IDL.Variant({
    'on_leave' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'markedBy' : IDL.Text,
  });
  
  return IDL.Service({
    'addFeeRecord' : IDL.Func([FeeRecord], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'addTeacher' : IDL.Func([Teacher], [], []),
    'deleteStudent' : IDL.Func([StudentId], [], []),
    'deleteTeacher' : IDL.Func([TeacherId], [], []),
    'getAcademicRecord' : IDL.Func([StudentId], [AcademicRecord], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMonthlyAttendance' : IDL.Func(
        [StudentId, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [Student], ['query']),
    'getStudentAttendance' : IDL.Func(
        [StudentId],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getStudentFees' : IDL.Func([StudentId], [IDL.Vec(FeeRecord)], ['query']),
    'getStudentsByClass' : IDL.Func([ClassName], [IDL.Vec(Student)], ['query']),
    'getStudentsByTeacher' : IDL.Func(
        [TeacherId],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getTeacher' : IDL.Func([TeacherId], [Teacher], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'markAttendance' : IDL.Func([Attendance], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAcademicRecord' : IDL.Func([AcademicRecord], [], []),
    'updateFeeStatus' : IDL.Func([FeeRecordId, FeesPaymentStatus], [], []),
    'updateStudent' : IDL.Func([StudentId, Student], [], []),
    'updateTeacher' : IDL.Func([TeacherId, Teacher], [], []),
  });
};

export const init = ({ IDL }) => { return []; };