/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicRecord {
  'id' : AcademicRecordId,
  'studentId' : StudentId,
  'monthlyProgress' : string,
  'updatedAt' : bigint,
  'previousSabak' : string,
  'currentSabak' : string,
  'akhlaqRating' : bigint,
}
export type AcademicRecordId = string;
export interface Attendance {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : string,
  'createdAt' : bigint,
  'markedBy' : string,
}
export type AttendanceId = string;
export type AttendanceStatus = { 'on_leave' : null } |
  { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export type ClassName = string;
export interface FeeRecord {
  'id' : FeeRecordId,
  'status' : FeesPaymentStatus,
  'month' : string,
  'studentId' : StudentId,
  'createdAt' : bigint,
  'amount' : bigint,
}
export type FeeRecordId = string;
export type FeesPaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null } |
  { 'partial_payment' : null };
export type FeesStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null };
export interface Student {
  'id' : StudentId,
  'timing' : string,
  'name' : string,
  'createdAt' : bigint,
  'feesStatus' : FeesStatus,
  'mobileNumber' : string,
  'assignedTeacherId' : TeacherId,
  'fatherName' : string,
  'monthlyFees' : bigint,
  'className' : ClassName,
}
export type StudentId = string;
export interface Teacher {
  'id' : TeacherId,
  'name' : string,
  'createdAt' : bigint,
  'mobileNumber' : string,
}
export type TeacherId = string;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'contactNumber' : string,
}
export interface _SERVICE {
  'addFeeRecord' : ActorMethod<[FeeRecord], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'addTeacher' : ActorMethod<[Teacher], undefined>,
  'deleteStudent' : ActorMethod<[StudentId], undefined>,
  'deleteTeacher' : ActorMethod<[TeacherId], undefined>,
  'getAcademicRecord' : ActorMethod<[StudentId], AcademicRecord>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMonthlyAttendance' : ActorMethod<[StudentId, string], Array<Attendance>>,
  'getStudent' : ActorMethod<[StudentId], Student>,
  'getStudentAttendance' : ActorMethod<[StudentId], Array<Attendance>>,
  'getStudentFees' : ActorMethod<[StudentId], Array<FeeRecord>>,
  'getStudentsByClass' : ActorMethod<[ClassName], Array<Student>>,
  'getStudentsByTeacher' : ActorMethod<[TeacherId], Array<Student>>,
  'getTeacher' : ActorMethod<[TeacherId], Teacher>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'markAttendance' : ActorMethod<[Attendance], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAcademicRecord' : ActorMethod<[AcademicRecord], undefined>,
  'updateFeeStatus' : ActorMethod<[FeeRecordId, FeesPaymentStatus], undefined>,
  'updateStudent' : ActorMethod<[StudentId, Student], undefined>,
  'updateTeacher' : ActorMethod<[TeacherId, Teacher], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];