/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ClassName = string;
export interface Attendance {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    createdAt: bigint;
    markedBy: string;
}
export type AttendanceId = string;
export type AcademicRecordId = string;
export interface Teacher {
    id: TeacherId;
    name: string;
    createdAt: bigint;
    mobileNumber: string;
}
export type TeacherId = string;
export type StudentId = string;
export interface AcademicRecord {
    id: AcademicRecordId;
    studentId: StudentId;
    monthlyProgress: string;
    updatedAt: bigint;
    previousSabak: string;
    currentSabak: string;
    akhlaqRating: bigint;
}
export interface FeeRecord {
    id: FeeRecordId;
    status: FeesPaymentStatus;
    month: string;
    studentId: StudentId;
    createdAt: bigint;
    amount: bigint;
}
export type FeeRecordId = string;
export interface UserProfile {
    name: string;
    role: string;
    contactNumber: string;
}
export interface Student {
    id: StudentId;
    timing: string;
    name: string;
    createdAt: bigint;
    feesStatus: FeesStatus;
    mobileNumber: string;
    assignedTeacherId: TeacherId;
    fatherName: string;
    monthlyFees: bigint;
    className: ClassName;
}
export enum AttendanceStatus {
    on_leave = "on_leave",
    present = "present",
    late = "late",
    absent = "absent"
}
export enum FeesPaymentStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue",
    partial_payment = "partial_payment"
}
export enum FeesStatus {
    active = "active",
    cancelled = "cancelled",
    pending = "pending"
}
export interface backendInterface {
    addFeeRecord(feeRecord: FeeRecord): Promise<void>;
    addStudent(student: Student): Promise<void>;
    addTeacher(teacher: Teacher): Promise<void>;
    deleteStudent(id: StudentId): Promise<void>;
    deleteTeacher(id: TeacherId): Promise<void>;
    getAcademicRecord(studentId: StudentId): Promise<AcademicRecord>;
    getAllStudents(): Promise<Array<Student>>;
    getAllTeachers(): Promise<Array<Teacher>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getMonthlyAttendance(studentId: StudentId, month: string): Promise<Array<Attendance>>;
    getStudent(id: StudentId): Promise<Student>;
    getStudentAttendance(studentId: StudentId): Promise<Array<Attendance>>;
    getStudentFees(studentId: StudentId): Promise<Array<FeeRecord>>;
    getStudentsByClass(className: ClassName): Promise<Array<Student>>;
    getStudentsByTeacher(teacherId: TeacherId): Promise<Array<Student>>;
    getTeacher(id: TeacherId): Promise<Teacher>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    markAttendance(attendanceRecord: Attendance): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAcademicRecord(record: AcademicRecord): Promise<void>;
    updateFeeStatus(id: FeeRecordId, status: FeesPaymentStatus): Promise<void>;
    updateStudent(id: StudentId, student: Student): Promise<void>;
    updateTeacher(id: TeacherId, teacher: Teacher): Promise<void>;
}
import type { Attendance as _Attendance, AttendanceId as _AttendanceId, AttendanceStatus as _AttendanceStatus, ClassName as _ClassName, FeeRecord as _FeeRecord, FeeRecordId as _FeeRecordId, FeesPaymentStatus as _FeesPaymentStatus, FeesStatus as _FeesStatus, Student as _Student, StudentId as _StudentId, TeacherId as _TeacherId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFeeRecord(arg0: FeeRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeeRecord(to_candid_FeeRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeeRecord(to_candid_FeeRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(to_candid_Student_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(to_candid_Student_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTeacher(arg0: Teacher): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacher(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: TeacherId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async getAcademicRecord(arg0: StudentId): Promise<AcademicRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademicRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademicRecord(arg0);
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeachers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyAttendance(arg0: StudentId, arg1: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyAttendance(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyAttendance(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Student_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Student_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendance(arg0: StudentId): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendance(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendance(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentFees(arg0: StudentId): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentFees(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentFees(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsByClass(arg0: ClassName): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClass(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClass(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsByTeacher(arg0: TeacherId): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByTeacher(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByTeacher(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: TeacherId): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAttendance(arg0: Attendance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(to_candid_Attendance_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(to_candid_Attendance_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAcademicRecord(arg0: AcademicRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAcademicRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAcademicRecord(arg0);
            return result;
        }
    }
    async updateFeeStatus(arg0: FeeRecordId, arg1: FeesPaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeStatus(arg0, to_candid_FeesPaymentStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeStatus(arg0, to_candid_FeesPaymentStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: StudentId, arg1: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_Student_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_Student_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTeacher(arg0: TeacherId, arg1: Teacher): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AttendanceStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Attendance_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FeeRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeRecord): FeeRecord {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_FeesPaymentStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeesPaymentStatus): FeesPaymentStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_FeesStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeesStatus): FeesStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    timing: string;
    name: string;
    createdAt: bigint;
    feesStatus: _FeesStatus;
    mobileNumber: string;
    assignedTeacherId: _TeacherId;
    fatherName: string;
    monthlyFees: bigint;
    className: _ClassName;
}): {
    id: StudentId;
    timing: string;
    name: string;
    createdAt: bigint;
    feesStatus: FeesStatus;
    mobileNumber: string;
    assignedTeacherId: TeacherId;
    fatherName: string;
    monthlyFees: bigint;
    className: ClassName;
} {
    return {
        id: value.id,
        timing: value.timing,
        name: value.name,
        createdAt: value.createdAt,
        feesStatus: from_candid_FeesStatus_n12(_uploadFile, _downloadFile, value.feesStatus),
        mobileNumber: value.mobileNumber,
        assignedTeacherId: value.assignedTeacherId,
        fatherName: value.fatherName,
        monthlyFees: value.monthlyFees,
        className: value.className
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: string;
    createdAt: bigint;
    markedBy: string;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    createdAt: bigint;
    markedBy: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n18(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        createdAt: value.createdAt,
        markedBy: value.markedBy
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeeRecordId;
    status: _FeesPaymentStatus;
    month: string;
    studentId: _StudentId;
    createdAt: bigint;
    amount: bigint;
}): {
    id: FeeRecordId;
    status: FeesPaymentStatus;
    month: string;
    studentId: StudentId;
    createdAt: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_FeesPaymentStatus_n23(_uploadFile, _downloadFile, value.status),
        month: value.month,
        studentId: value.studentId,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    pending: null;
}): FeesStatus {
    return "active" in value ? FeesStatus.active : "cancelled" in value ? FeesStatus.cancelled : "pending" in value ? FeesStatus.pending : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    on_leave: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "on_leave" in value ? AttendanceStatus.on_leave : "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} | {
    partial_payment: null;
}): FeesPaymentStatus {
    return "pending" in value ? FeesPaymentStatus.pending : "paid" in value ? FeesPaymentStatus.paid : "overdue" in value ? FeesPaymentStatus.overdue : "partial_payment" in value ? FeesPaymentStatus.partial_payment : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeRecord>): Array<FeeRecord> {
    return value.map((x)=>from_candid_FeeRecord_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Attendance_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attendance): _Attendance {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_FeeRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeRecord): _FeeRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FeesPaymentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeesPaymentStatus): _FeesPaymentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FeesStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeesStatus): _FeesStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Student_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): _Student {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FeeRecordId;
    status: FeesPaymentStatus;
    month: string;
    studentId: StudentId;
    createdAt: bigint;
    amount: bigint;
}): {
    id: _FeeRecordId;
    status: _FeesPaymentStatus;
    month: string;
    studentId: _StudentId;
    createdAt: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_FeesPaymentStatus_n3(_uploadFile, _downloadFile, value.status),
        month: value.month,
        studentId: value.studentId,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    createdAt: bigint;
    markedBy: string;
}): {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: string;
    createdAt: bigint;
    markedBy: string;
} {
    return {
        id: value.id,
        status: to_candid_AttendanceStatus_n27(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        createdAt: value.createdAt,
        markedBy: value.markedBy
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: StudentId;
    timing: string;
    name: string;
    createdAt: bigint;
    feesStatus: FeesStatus;
    mobileNumber: string;
    assignedTeacherId: TeacherId;
    fatherName: string;
    monthlyFees: bigint;
    className: ClassName;
}): {
    id: _StudentId;
    timing: string;
    name: string;
    createdAt: bigint;
    feesStatus: _FeesStatus;
    mobileNumber: string;
    assignedTeacherId: _TeacherId;
    fatherName: string;
    monthlyFees: bigint;
    className: _ClassName;
} {
    return {
        id: value.id,
        timing: value.timing,
        name: value.name,
        createdAt: value.createdAt,
        feesStatus: to_candid_FeesStatus_n7(_uploadFile, _downloadFile, value.feesStatus),
        mobileNumber: value.mobileNumber,
        assignedTeacherId: value.assignedTeacherId,
        fatherName: value.fatherName,
        monthlyFees: value.monthlyFees,
        className: value.className
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    on_leave: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.on_leave ? {
        on_leave: null
    } : value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeesPaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} | {
    partial_payment: null;
} {
    return value == FeesPaymentStatus.pending ? {
        pending: null
    } : value == FeesPaymentStatus.paid ? {
        paid: null
    } : value == FeesPaymentStatus.overdue ? {
        overdue: null
    } : value == FeesPaymentStatus.partial_payment ? {
        partial_payment: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeesStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    pending: null;
} {
    return value == FeesStatus.active ? {
        active: null
    } : value == FeesStatus.cancelled ? {
        cancelled: null
    } : value == FeesStatus.pending ? {
        pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
